// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using freemarketmusic.Shared;

namespace freemarketmusic.Server.models
{
    public partial class FMMContext : DbContext
    {
        public FMMContext()
        {
        }

        public FMMContext(DbContextOptions<FMMContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FileDatum> FileData { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<FileDatum>(entity =>
            {
                entity.HasKey(e => e.FileId)
                    .HasName("PK__FileData__6F0F98BFFC39B89A");

                entity.Property(e => e.FileName).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}